CREATE TABLE card
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    activated     BOOLEAN NOT NULL,
    card_no       INT     NOT NULL,
    issuer_code   INT     NOT NULL,
    card_type     SMALLINT,
    expirary_date TIMESTAMP,
    user_id       BIGINT,
    CONSTRAINT pk_card PRIMARY KEY (id)
);

CREATE TABLE issuer
(
    issuer_id   BIGINT NOT NULL,
    issuer_code INT    NOT NULL,
    issuer_name INT    NOT NULL,
    card_id     BIGINT NOT NULL,
    user_id     BIGINT,
    CONSTRAINT pk_issuer PRIMARY KEY (issuer_id)
);

CREATE TABLE "user"
(
    user_id              BIGINT NOT NULL,
    firstname            VARCHAR(255),
    lastname             VARCHAR(255),
    account_no           INT    NOT NULL,
    shipping_address     VARCHAR(255),
    uid                  VARCHAR(255),
    national_code        INT    NOT NULL,
    card_no              INT    NOT NULL,
    phone_no             INT    NOT NULL,
    authentication_token VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

ALTER TABLE issuer
    ADD CONSTRAINT uc_issuer_issuercode UNIQUE (issuer_code);

ALTER TABLE card
    ADD CONSTRAINT FK_CARD_ON_USERID FOREIGN KEY (user_id) REFERENCES "user" (id);
CREATE TABLE issuer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuer_code INT                                     NOT NULL,
    issuer_name INT                                     NOT NULL,
    CONSTRAINT pk_issuer PRIMARY KEY (id)
);


ALTER TABLE card
    ADD CONSTRAINT FK_CARD_ON_ID FOREIGN KEY (id) REFERENCES "user" (id);

ALTER TABLE card
    ADD CONSTRAINT FK_CARD_ON_IDFHWRvk FOREIGN KEY (id) REFERENCES issuer (id);

ALTER TABLE issuer
    ADD CONSTRAINT FK_ISSUER_ON_ID FOREIGN KEY (id) REFERENCES card (id);

ALTER TABLE issuer
    ADD CONSTRAINT FK_ISSUER_ON_IDcAhUEn FOREIGN KEY (id) REFERENCES "user" (id);

ALTER TABLE CARD
    DROP COLUMN USER_ID;