CREATE TABLE "user"
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname            VARCHAR(15),
    lastname             VARCHAR(15),
    account_no           INT,
    shipping_address     VARCHAR(40),
    national_code        INT,
    card_no              INT,
    phone_no             INT,
    authentication_token VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);


CREATE TABLE card
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    activated      BOOLEAN,
    card_no        INT                                     NOT NULL,
    issuer_code    INT                                     NOT NULL,
    card_type      SMALLINT,
    expirary_date  TIMESTAMP,
    issuer_id      BIGINT,
    user_id        BIGINT,
    issuer_user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_card PRIMARY KEY (id)
);


CREATE TABLE issuer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuer_code INT                                     NOT NULL,
    issuer_name INT                                     NOT NULL,
    user_id     BIGINT,
    CONSTRAINT pk_issuer PRIMARY KEY (id)
);

ALTER TABLE issuer
    ADD CONSTRAINT uc_issuer_issuercode UNIQUE (issuer_code);

ALTER TABLE issuer
    ADD CONSTRAINT FK_ISSUER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);