version: '3.8'
services:
    customer-card-service:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
        - SPRING_DATASOURCE_USERNAME=sa
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      depends_on:
        - h2-database

    h2-database:
      image: oscarfonts/h2
      ports:
        - "9092:9092"
      environment:
        - H2_OPTIONS=-ifNotExists

